# Google Cloud Build配置文件
steps:
  # 構建Python應用程式
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'python-app/app.yaml'
      - '--project=$PROJECT_ID'
      - '--version=$SHORT_SHA'
      - '--promote'
    dir: '.'
    
  # 構建N8n Docker映像
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/n8n:$SHORT_SHA'
      - '-f'
      - 'docker/n8n.Dockerfile'
      - '.'
    
  # 推送N8n映像到Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/n8n:$SHORT_SHA'
    
  # 部署N8n到Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'n8n-service'
      - '--image=gcr.io/$PROJECT_ID/n8n:$SHORT_SHA'
      - '--platform=managed'
      - '--region=asia-east1'
      - '--allow-unauthenticated'
      - '--port=5678'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--max-instances=3'
      - '--set-env-vars=N8N_HOST=n8n-service-hash-uc.a.run.app'
      - '--set-env-vars=N8N_PROTOCOL=https'
      - '--set-env-vars=WEBHOOK_URL=https://n8n-service-hash-uc.a.run.app'

# 替代變數
substitutions:
  _REGION: 'asia-east1'

# 構建選項
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# 超時設定
timeout: '1200s'