# Google App Engine configuration
runtime: python311
instance_class: F2

# Environment variables
env_variables:
  FLASK_ENV: "production"

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Handlers for URL routing
handlers:
  # Static files
  - url: /static
    static_dir: static
    
  # API endpoints
  - url: /api/.*
    script: auto
    secure: always
    
  # Health check
  - url: /_ah/health
    script: auto
    
  # Main application
  - url: /.*
    script: auto
    secure: always